//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDI_ICON1                       101
#define IDD_ABOUT                       102
#define DIAL_PLAY                       103
#define IDB_VNCLOGO                     132
#define IDB_CHECK                       133
#define IDB_CLOCKSAND                   134
#define IDB_KEY                         135
#define IDB_WOODU                       136
#define IDB_WOODD                       137
#define IDB_MICRO                       138
#define IDB_MICROON                     139
#define IDB_RITMOY                      140
#define IDB_RITMON                      141
#define IDB_OKAY                        142
#define IDB_OKAN                        143
#define IDB_CFG                         144
#define IDB_GAME1                       145
#define IDB_GAME2                       146
#define IDB_GAME3                       147
#define IDB_GAME4                       148
#define IDB_SPLASH                      149
#define IDB_EARN                        150
#define IDB_EARY                        151
#define IDB_REPE                        152
#define IDB_CFGY                        153
#define IDB_GAME5                       154
#define IDB_HANDL                       155
#define IDB_HANDR                       156
#define IDB_HANDLL                      157
#define IDB_HANDRL                      158
#define IDB_OKAYH                       159
#define IDB_OKANH                       160
#define IDB_GAME6                       161
#define IDB_PLAYN                       162
#define IDB_PLAYY                       163
#define IDB_GOTO                        164
#define IDC_VNCLOGO                     1006
#define IDC_FINGER                      1007
#define IDC_BUILDTIME                   1103
#define IDC_STATIC_MAIL                 1105
#define IDC_STATIC_URL                  1107
#define IDC_STATIC_VERSION              1108
#define IDC_STATIC_COPYRIGHTS           1109
#define IDC_STATIC_BASEDON              1110
#define DIAL_APPR                       3100
#define IDC_COMPAS                      3101
#define IDC_MAXINTERSOL                 3102
#define IDC_MININTERSOL                 3103
#define IDC_MAXINTERFA                  3104
#define IDC_MININTERFA                  3105
#define IDC_ARMA                        3106
#define IDC_NUMCOMPAS                   3107
#define IDC_FINGUERY                    3108
#define IDC_BLOQSOL                     3109
#define IDC_BLOQFA                      3110
#define IDC_BLOQFA2                     3111
#define IDC_REPEATG                     3112
#define IDC_REPEATF                     3113
#define IDC_NOTERESE                    3114
#define IDC_METRONOMO                   3115
#define IDC_MAXCOMPASCREEN              3117
#define IDC_FINGUERN                    3118
#define IDC_RITMOY                      3119
#define IDC_RITMON                      3120
#define IDC_RANDMODE                    3121
#define IDC_MAXINTERSOL_NOTEINT         3122
#define IDC_MININTERSOL_NOTEINT         3123
#define IDC_MAXINTERFA_NOTEINT          3124
#define IDC_MININTERFA_NOTEINT          3125
#define IDC_MAXINTERVAL_FLASHNOTEINT    3126
#define IDC_MININTERVAL_FLASHNOTEINT    3127
#define IDC_MAXVARIACION                3128
#define IDC_SILENCION                   3129
#define IDC_SILENCIOY                   3130
#define IDC_ACCURACYNOTES               3131
#define IDC_ACCURACYTEMPO               3132
#define IDC_ARMANOTEREADING             3133
#define IDC_ARMANOTEINTERVAL            3134
#define IDC_SINGOCTAVAY                 3135
#define IDC_SINGOCTAVAN                 3136
#define IDC_NOTEREADINGACCIY            3137
#define IDC_NOTEREADINGACCIN            3138
#define IDC_STOPONERRORY                3139
#define IDC_STOPONERRORN                3140
#define IDC_RANDOMMUSICACCIY            3141
#define IDC_RANDOMMUSICACCIN            3142
#define IDC_MAXINTERSOL_NOTEREAD        3143
#define IDC_MININTERSOL_NOTEREAD        3144
#define IDC_MAXINTERFA_NOTEREAD         3145
#define IDC_MININTERFA_NOTEREAD         3146
#define DIAL_INFORM                     3147
#define IDC_EAROCTAVAY                  3148
#define IDC_EAROCTAVAN                  3149
#define IDC_MINTONO_EARNOTEREAD         3150
#define IDC_MAXTONO_EARNOTEREAD         3151
#define IDC_OIDOABSOLUTO                3152
#define IDC_OIDORELATIVO                3153
#define IDC_SOLFEOHABLADO               3154
#define IDC_SOLFEOCANTADO               3155
#define IDC_OCULTANOTA                  3156
#define IDC_RITMOASISN                  3157
#define IDC_RITMOASISY                  3158
#define IDC_SIGUEMEN                    3159
#define IDC_SIGUEMEY                    3160
#define IDR_WAVE1                       3161
#define IDB_METROY                      3162
#define IDB_METRON                      3163
#define IDC_REPMALRITMON                3164
#define IDC_REPMALRITMOY                3165
#define IDC_OPENFILE                    3166
#define DIAL_GOTO                       3167
#define IDC_GOTOCOMPAS                  3168
#define IDC_NOTEREADINGCHORDY           3169
#define IDC_NOTEREADINGCHORDN           3170
#define IDC_NOTEREADINGFIGURY           3171
#define IDC_NOTEREADINGFIGURN           3172
#define IDC_NOTEREADINGDEEPY            3173
#define IDC_NOTEREADINGDEEPN            3174
#define IDC_NOTEREADINGMEMO             3175
#define IDC_NOTEREADINGLEADY            3176
#define IDC_NOTEREADINGLEADN            3177
#define IDC_RANDOMMUSICQOSRITMON        3178
#define IDC_RANDOMMUSICQOSRITMOY        3179
#define IDC_PLAYONLYACT                 3180
#define IDC_PLAYFROMACT                 3181
#define IDC_RANDOMMUSICQOSCOMPASN       3182
#define IDC_RANDOMMUSICQOSCOMPASY       3183
#define IDC_RANDOMMUSICQOSLEGATON       3184
#define IDC_RANDOMMUSICQOSLEGATOY       3185
#define DIAL_EJE1                       3186
#define DIAL_EJE3                       3188
#define DIAL_EJE4                       3189
#define DIAL_EJE6                       3191
#define IDC_NOTEREADINGFINGERY          3192
#define IDC_NOTEREADINGFINGERN          3193
#define IDC_NOTEREADQOSRITMON           3194
#define IDC_NOTEREADQOSRITMOY           3195
#define IDC_NOTEREADQOSLEGATON          3196
#define IDC_NOTEREADQOSLEGATOY          3197
#define IDC_SOLORITMON                  3198
#define IDC_SOLORITMOY                  3199

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
